//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMarketplace.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusHistory
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime DateChanged { get; set; }
        public bool IsActual { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
    }
}
